# Generated by Django 6.0.2 on 2026-04-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_notification_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantcall',
            name='last_called_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='command',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
