# Generated by Django 6.0.2 on 2026-04-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_assistantcall_last_called_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantcall',
            name='last_called_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
