# Generated by Django 6.0.2 on 2026-04-15 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_assistantcall_last_called_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='assistant_id',
        ),
        migrations.RemoveField(
            model_name='command',
            name='assistant_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_command',
            field=models.ForeignKey(blank=True, help_text='Currently active command whose prompt is appended to the assistant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.command'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assistant_id',
            field=models.CharField(blank=True, help_text='Single Vapi assistant ID for this user (created during voice setup)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='menu_pin',
            field=models.CharField(blank=True, default='', help_text='4-digit PIN used to gate access to the menu/commands page', max_length=4),
        ),
    ]
